[project]
name = "test-init-bubble"
version = "0.0.1"

[defaults]
iterations = 1000
warmup = 100
languages = [
    "ts",
    "go",
    "c",
]

[go]
module = "test-init-bubble"
version = "1.21"

[ts]
runtime = "node"

[c]
standard = "c11"

[output]
report_formats = []
output_dir = "out"
auto_save_results = true
