[project]
name = "demo-project"
version = "0.1.0"

[defaults]
iterations = 1000
warmup = 100
languages = [
    "go",
    "ts",
]

[go]
module = "demo-project"
version = "1.21"

[ts]
runtime = "node"

[output]
report_formats = []
