[project]
name = "rel-deme"
version = "0.1.0"

[defaults]
iterations = 1000
warmup = 100
languages = [
    "go",
    "ts",
]

[go]
module = "rel-deme"
version = "1.21"

[ts]
runtime = "node"

[output]
report_formats = []
output_dir = "out"
auto_save_results = true
