[project]
name = "demo"
version = "0.1.0"

[defaults]
iterations = 1000
warmup = 0
languages = [
    "go",
    "ts",
]

[go]
module = "demo"
version = "1.21"

[go.dependencies]
"github.com/ChefBingbong/viem-go" = "latest"

[ts]
runtime = "node"

[ts.dependencies]
viem = "latest"

[output]
report_formats = []
output_dir = "out"
auto_save_results = true
